version: "3.8"

services:
  php:
    container_name: weather_app1
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/weather_app
  nginx:
    container_name: weather_app_nginx1
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/weather_app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php